# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: echo Hello, world!
#   displayName: 'Run a one-line script'
# - task: Maven@4
#   inputs:
#     mavenPomFile: 'pom.xml'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     javaHomeOption: 'JDKVersion'
#     mavenVersionOption: 'Default'
#     mavenAuthenticateFeed: false
#     effectivePomSkip: false
#     sonarQubeRunAnalysis: false

- task: Docker@2
  inputs:
    containerRegistry: 'docker-connection'
    repository: 'devazuredevops-demo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker image'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws-azuedevops'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'devazuredevops-demo'
    sourceImageTag: '$(Build.BuildId)'
    repositoryName: 'devazuredevops-demo'
    pushTag: '$(Build.BuildId)'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      helm upgrade --install hello-java ./hello-java-chart \
            --namespace default \
            --set image.tag=$(IMAGE_TAG)