replicaCount: 1

image:
  repository: 311141542585.dkr.ecr.us-east-1.amazonaws.com/devazuredevops-demo:270
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

